version: '3.8'

services:
  vastai-interup:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.pytorch.fat
    image: registry.gitlab.com/gfever/vastai_interup:pytorch-fat-291225
    container_name: vastai_interup_dev
    entrypoint: /bin/bash
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - DISABLE_MODEL_SOURCE_CHECK=True
      - PROPAINTER_ROOT=/opt/ProPainter
      - PYTHONPATH=/workspace/project/src:/opt/ProPainter
      - LOG_LEVEL=INFO
      - TQDM_DISABLE=False
      - LD_LIBRARY_PATH=/opt/venv/lib/python3.10/site-packages/nvidia/cudnn/lib:/opt/venv/lib/python3.10/site-packages/nvidia/cublas/lib:$LD_LIBRARY_PATH
    volumes:
      - .:/workspace/project
    working_dir: /workspace/project
    #command: -c "python docker/check_gpu.py && echo 'GPU check completed. Ready for processing.' && bash"
    command: -c "tail -f /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
